import streamlit as st
from document_loader import load_documents, chunk_text
from embeddings import create_embeddings, store_embeddings
from retriever import retrieve_chunks
from generator import generate_answer, summarize_document, evaluate_answer
import os
import tempfile
from fpdf import FPDF

def generate_chat_pdf(messages, language):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(0, 119, 182)
    pdf.cell(0, 15, "Multilingual RAG System Agent", ln=True, align='C')
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Chat History | Language: {language}", ln=True, align='C')
    pdf.ln(5)
    pdf.set_draw_color(0, 119, 182)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(8)
    for i, message in enumerate(messages):
        if message['role'] == 'user':
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(30, 58, 95)
            pdf.cell(0, 8, f"Question {(i//2)+1}:", ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(0, 0, 0)
            pdf.multi_cell(0, 7, message['content'])
            pdf.ln(3)
        else:
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(0, 119, 182)
            pdf.cell(0, 8, "Answer:", ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(0, 0, 0)
            answer = message['content'].encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 7, answer)
            pdf.ln(3)
            if 'evaluation' in message:
                score = message['evaluation']['faithfulness_score']
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(100, 100, 100)
                pdf.cell(0, 7, f"Faithfulness Score: {score}/100 | Retrieval: {message['evaluation']['retrieval_quality']} | Problem: {message['evaluation']['problem_area']}", ln=True)
                pdf.set_font("Helvetica", "I", 9)
                diagnosis = message['evaluation']['diagnosis'].encode('latin-1', 'replace').decode('latin-1')
                pdf.cell(0, 7, f"Diagnosis: {diagnosis}", ln=True)
            if 'sources' in message:
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(0, 119, 182)
                sources = list(set(message['sources']))
                pdf.cell(0, 7, f"Sources: {', '.join(sources)}", ln=True)
            pdf.ln(3)
            pdf.set_draw_color(200, 200, 200)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(5)
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, "Generated by Multilingual RAG System Agent | Built by Akhil Kadapa", align='C')
    return bytes(pdf.output())


# Page config
st.set_page_config(
    page_title="Multilingual RAG System Agent",
    layout="wide",
    initial_sidebar_state="expanded"
)

# CSS
st.markdown("""
<style>
    .main { background-color: #0e1117; }
    .stApp { background-color: #0e1117; }
    .chat-message-user {
        background-color: #1e3a5f;
        padding: 15px;
        border-radius: 10px;
        margin: 10px 0;
        color: white;
    }
    .chat-message-ai {
        background-color: #1a1a2e;
        padding: 15px;
        border-radius: 10px;
        margin: 10px 0;
        color: white;
        border-left: 3px solid #00b4d8;
    }
    .score-high { color: #00ff88; font-weight: bold; }
    .score-medium { color: #ffaa00; font-weight: bold; }
    .score-low { color: #ff4444; font-weight: bold; }
    .source-badge {
        background-color: #16213e;
        padding: 5px 10px;
        border-radius: 15px;
        margin: 3px;
        display: inline-block;
        color: #00b4d8;
        font-size: 12px;
    }
    div[data-testid="stExpander"] div[role="region"] {
        max-height: 400px;
        overflow-y: auto;
    }
</style>
""", unsafe_allow_html=True)

# Session state
if "messages" not in st.session_state:
    st.session_state.messages = []
if "index" not in st.session_state:
    st.session_state.index = None
if "chunks" not in st.session_state:
    st.session_state.chunks = None
if "processed" not in st.session_state:
    st.session_state.processed = False
if "summaries" not in st.session_state:
    st.session_state.summaries = []

# Sidebar — language and stats only
with st.sidebar:
    st.title("Multilingual RAG")
    st.caption("Search smarter across languages")
    st.divider()

    st.subheader("Output Language")
    language = st.selectbox(
        "Select language",
        ["English", "Telugu", "Hindi", "French", "Spanish"],
        key="language"
    )

    st.divider()

    st.subheader("📁 Upload Documents")
    uploaded_files_sidebar = st.file_uploader(
        "Upload PDF or TXT files",
        type=["pdf", "txt"],
        accept_multiple_files=True,
        key="sidebar_upload"
    )

    if uploaded_files_sidebar:
        if st.button("🚀 Process Documents", use_container_width=True, type="primary"):
            progress_bar = st.progress(0)
            status_text = st.empty()

            status_text.text("Reading documents...")
            progress_bar.progress(20)

            temp_dir = tempfile.mkdtemp()
            for uploaded_file in uploaded_files_sidebar:
                file_path = os.path.join(temp_dir, uploaded_file.name)
                with open(file_path, "wb") as f:
                    f.write(uploaded_file.getbuffer())

            documents = load_documents(temp_dir)

            seen = set()
            unique_docs = []
            for doc in documents:
                if doc['filename'] not in seen:
                    seen.add(doc['filename'])
                    unique_docs.append(doc)
            documents = unique_docs

            if documents:
                status_text.text("Generating summaries...")
                progress_bar.progress(40)

                st.session_state.summaries = []
                for doc in documents:
                    summary = summarize_document(
                        doc['text'],
                        doc['filename'],
                        language
                    )
                    st.session_state.summaries.append({
                        "filename": doc['filename'],
                        "summary": summary
                    })

                status_text.text("Chunking documents...")
                progress_bar.progress(60)

                all_chunks = []
                for doc in documents:
                    chunks = chunk_text(doc['text'], doc['filename'])
                    all_chunks.extend(chunks)

                status_text.text("Creating embeddings...")
                progress_bar.progress(80)

                embeddings = create_embeddings(all_chunks)
                index, chunks = store_embeddings(embeddings, all_chunks)

                status_text.text("Ready!")
                progress_bar.progress(100)

                st.session_state.index = index
                st.session_state.chunks = chunks
                st.session_state.processed = True
                st.session_state.messages = []

                st.success(f"✅ {len(documents)} documents processed!")
                st.rerun()

    st.divider()

    if st.session_state.processed:
        st.subheader("📊 Stats")
        st.metric("📁 Documents", len(st.session_state.summaries))
        st.metric("🌍 Language", language)
        st.metric("✅ Status", "Ready")

# Main area
st.title("Multilingual RAG System Agent")
st.caption("Search smarter across languages")
st.divider()

# If documents processed — show chat
if st.session_state.processed and st.session_state.summaries:

    with st.expander("📄 Document Summaries", expanded=True):
        for i, summary in enumerate(st.session_state.summaries):
            st.markdown(f"**📌 {summary['filename']}**")
            st.info(summary['summary'])
            if i < len(st.session_state.summaries) - 1:
                st.divider()

    # Chat history
    for message in st.session_state.messages:
        if message['role'] == 'user':
            st.markdown(f"""
            <div class="chat-message-user">
            <b>You:</b> {message['content']}
            </div>
            """, unsafe_allow_html=True)
        else:
            st.markdown(f"""
            <div class="chat-message-ai">
            <b>AI:</b> {message['content']}
            </div>
            """, unsafe_allow_html=True)

            if 'evaluation' in message:
                score = message['evaluation']['faithfulness_score']
                col1, col2, col3 = st.columns(3)
                with col1:
                    st.markdown("**Faithfulness Score**")
                    st.progress(score/100)
                    if score >= 80:
                        st.markdown(f"<span class='score-high'>{score}/100 Excellent</span>", unsafe_allow_html=True)
                    elif score >= 50:
                        st.markdown(f"<span class='score-medium'>{score}/100 Average</span>", unsafe_allow_html=True)
                    else:
                        st.markdown(f"<span class='score-low'>{score}/100 Poor</span>", unsafe_allow_html=True)
                with col2:
                    st.markdown("**Retrieval Quality**")
                    if message['evaluation']['retrieval_quality'] == "Good":
                        st.success("Good")
                    else:
                        st.error("Bad")
                with col3:
                    st.markdown("**Problem Area**")
                    if message['evaluation']['problem_area'] == "None":
                        st.success("None")
                    else:
                        st.warning(message['evaluation']['problem_area'])
                st.caption(f"{message['evaluation']['diagnosis']}")

            if 'sources' in message:
                st.markdown("**Sources:**")
                for source in set(message['sources']):
                    st.markdown(f"<span class='source-badge'>{source}</span>", unsafe_allow_html=True)

            st.divider()

    # Download button
    if st.session_state.messages:
        pdf_data = generate_chat_pdf(st.session_state.messages, language)
        st.download_button(
            label="Download PDF",
            data=pdf_data,
            file_name="multilingual_rag_chat.pdf",
            mime="application/pdf",
            use_container_width=True
        )

    st.divider()

    # Question input
    question = st.chat_input("Ask anything about your documents...")

    if question:
        st.session_state.messages.append({
            'role': 'user',
            'content': question
        })
        with st.spinner("Thinking..."):
            relevant_chunks = retrieve_chunks(
                question,
                st.session_state.index,
                st.session_state.chunks
            )
            result = generate_answer(question, relevant_chunks, language)
            evaluation = evaluate_answer(question, result['answer'], relevant_chunks)

        st.session_state.messages.append({
            'role': 'assistant',
            'content': result['answer'],
            'sources': result['sources'],
            'evaluation': evaluation
        })
        st.rerun()

# If not processed — show centered upload
else:
    st.markdown("<br>", unsafe_allow_html=True)
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        uploaded_files = st.file_uploader(
            "📁 Upload Documents",
            type=["pdf", "txt"],
            accept_multiple_files=True,
            help="Click to upload PDF or TXT files up to 200MB"
        )

        if not uploaded_files:
            st.markdown("""
            <div style='text-align: center; padding: 20px;
            color: #555; font-size: 13px;'>
                Supports PDF and TXT files • Multiple files allowed
            </div>
            """, unsafe_allow_html=True)

        if uploaded_files:
            st.markdown("**Uploaded Files:**")
            for f in uploaded_files:
                st.markdown(f"✅ {f.name} ({round(f.size/1024, 1)} KB)")

            if st.button("Process Documents", use_container_width=True, type="primary"):
                progress_bar = st.progress(0)
                status_text = st.empty()

                status_text.text("Reading documents...")
                progress_bar.progress(20)

                temp_dir = tempfile.mkdtemp()
                for uploaded_file in uploaded_files:
                    file_path = os.path.join(temp_dir, uploaded_file.name)
                    with open(file_path, "wb") as f:
                        f.write(uploaded_file.getbuffer())

                documents = load_documents(temp_dir)

                seen = set()
                unique_docs = []
                for doc in documents:
                    if doc['filename'] not in seen:
                        seen.add(doc['filename'])
                        unique_docs.append(doc)
                documents = unique_docs

                if documents:
                    status_text.text("Generating summaries...")
                    progress_bar.progress(40)

                    st.session_state.summaries = []
                    for doc in documents:
                        summary = summarize_document(
                            doc['text'],
                            doc['filename'],
                            language
                        )
                        st.session_state.summaries.append({
                            "filename": doc['filename'],
                            "summary": summary
                        })

                    status_text.text("Chunking documents...")
                    progress_bar.progress(60)

                    all_chunks = []
                    for doc in documents:
                        chunks = chunk_text(doc['text'], doc['filename'])
                        all_chunks.extend(chunks)

                    status_text.text("Creating embeddings...")
                    progress_bar.progress(80)

                    embeddings = create_embeddings(all_chunks)
                    index, chunks = store_embeddings(embeddings, all_chunks)

                    status_text.text("Ready!")
                    progress_bar.progress(100)

                    st.session_state.index = index
                    st.session_state.chunks = chunks
                    st.session_state.processed = True
                    st.session_state.messages = []

                    st.success(f"{len(documents)} documents processed!")
                    st.rerun()